#!/bin/bash
#SBATCH -N 1
#SBATCH -p short
#SBATCH -t 24:00:00
#SBATCH -n 1
#SBATCH --cpus-per-task=28
#SBATCH --mem=32G

source /home/y.qi/miniconda3/etc/profile.d/conda.sh
conda activate sLagSearch
#python points_generation.py 1024
for i in 10000000
#for i in 10000000 100000000
do
python points_generation.py --seed 1024 --psi $i
done
#for i in $(seq 91 100)
#do
#  python points_generation.py $i
#done
